### PR TITLE
Fix for domains that begin with localhost and 127.0.0.1

### PR DESCRIPTION
**Pull request by alexmozzhakov**
ex. [localhost.us](https://localhost.us)

### CODE REVIEW

**Comment by yungtravla** [comment]
@alexmozzhakov removing the port seems right but I don't think `localhost` is affected in any way by this

**Comment by yungtravla** [comment]
@alexmozzhakov is this the issue you are referring to?

screenshot from 2018-06-25 01-13-55

**Comment by alexmozzhakov** [comment]
@yungtravla yeah, was just getting this annoying warning and tried fixing without changing the logic. I have no idea why we may somehow proxy localhost connections at all. As I see it is that such  "blacklist" may be used for proxy whitelisting with `set http.proxy.whitelist` for ex.

**Comment by yungtravla** [comment]
@alexmozzhakov `localhost` and `localhost.com` are very different hosts.

`localhost` will loop back, whereas `localhost.com` is an actual endpoint.

**Comment by alexmozzhakov** [comment]
@yungtravla that's why it's shouldn't be blacklisted and throw a warning. Also, sry for a confusion, I meant whitelist from proxy = add to proxy blacklist = not proxy a specific domain (may be an issue with exactly the same code while trying to set adresses with ports)

**Comment by yungtravla** [comment]
@alexmozzhakov please explain to me how you are going to get an incoming connection from a hostname? DNS is not part of inbound connections unless you resolve it, and that could time out the request.

**Comment by yungtravla** [comment]
@alexmozzhakov I think this PR fixes an issue where incoming connections from 127.0.0.1 are not dropped.

**Comment by yungtravla** [comment]
I like the idea of `http.proxy.whitelist` and `http.proxy.blacklist`

**Comment by yungtravla** [comment]
@alexmozzhakov actually, I think the original code was fine.

You are not going to get incoming connections from `localhost.com`, that just doesn't happen. You can however receive incoming connections from `127.0.0.1:54863`, `127.0.0.1:54873`, `127.0.0.1:54864` as for example your browser uses different ports.

**Comment by alexmozzhakov** [comment]
@yungtravla out...comming 🤔 regular HTTP GET from proxied device to localhost.com throws ` [sys.log] [err] Got request with blacklisted host: localhost.com`😕

**Comment by yungtravla** [comment]
@alexmozzhakov you're right, I was getting confused. My bad.

This should indeed fix both issues you mentioned.

**Pull request merged**
