### PR TITLE
new: Implemented Rogue MySQL server module

### PR DESCRIPTION
**Pull request by bmaia**
This is a Rogue MySQL Server that steals client files via the LOCAL INFILE trick. I wrote about this technique here:

https://w00tsec.blogspot.nl/2018/04/abusing-mysql-local-infile-to-read.html

There's still some room for improvement, but it works fine for text files so far.

### CODE REVIEW

**Comment by evilsocket** [comment]
Dude, this is amazing! Thanks (also because I didn't know about this technique :D)

**Comment by evilsocket** [comment]
any chance you could write the Wiki page for the module? This is the template from the `http.server` one ... tnx <3 https://pastebin.com/7rCbnmJM

**Comment by bmaia** [comment]
I was waiting for the pull request before writing the Wiki documentation =)

Here's it: https://pastebin.com/fiC93fXt

**Comment by evilsocket** [comment]
https://github.com/bettercap/bettercap/wiki/mysql.server

**Pull request merged**
