### PR TITLE
Switch to go modules and fix tests

### PR DESCRIPTION
**Pull request by rumpelsepp**
This one enables support for go modules. Dependencies are managed by the go tool itself. I took the liberty to update all dependencies as well and I removed all vendored code, since the go tooling now downloads everything automatically.

### CODE REVIEW

**Comment by rumpelsepp** [comment]
Tests are broken. I will fix them.

**Comment by rumpelsepp** [comment]
Is ready to merge. I left a few TODOs for tests which I didn't manage to fix by now.

**Comment by mrbluecoat** [comment]
Any ETA on this?  It's a big diff and I'd prefer to wait to fork until after it lands if you're planning to accept it.

**Comment by evilsocket** [comment]
@mrbluecoat checking it right now

**Comment by evilsocket** [comment]
merged :D

**Pull request merged**
