### PR TITLE
Potential Code-Refactor and Bug Fixes 

### PR DESCRIPTION
**Pull request by HarshCasper**
## Description

Summary of fixes:

- Remove unnecessary guard around `delete`
- Remove unnecessary comparison with bool
- Added .deepsource.toml

## Importance

I ran a DeepSource Analysis on my fork of this repository. You can see all the issues raised by DeepSource [here](https://deepsource.io/gh/HarshCasper/bettercap).

DeepSource helps you to automatically find and fix issues in your code during code reviews. This tool looks for anti-patterns, bug risks, performance problems, and raises issues. There are plenty of other issues in relation to Bug Discovery and Anti-Patterns which you would be interested to take a look at.

If you do not want to use DeepSource to continuously analyze this repo, I'll remove the `.deepsource.toml` from this PR and you can merge the rest of the fixes. If you want to setup DeepSource for Continuous Analysis, I can help you set that up.

### CODE REVIEW

**Comment by HarshCasper** [comment]
Hi @evilsocket 

Can you kindly have a look at this PR? Thank You!

**Comment by evilsocket** [comment]
not going to merge until .deepsource.toml is there, not interested in integrating with additional services

**Comment by HarshCasper** [comment]
> not going to merge until .deepsource.toml is there, not interested in integrating with additional services

Hi @evilsocket 

I have removed the configuration now: Can you have a look again?

**Comment by evilsocket** [comment]
merged, thanks! :D

**Comment by HarshCasper** [comment]
Thanks @evilsocket 

I would work further on fixing the rest of the Issues as raised by the DeepSource 😄🙌

**Comment by evilsocket** [comment]
thanks!!!

**Pull request merged**
