### PR TITLE
modules/wifi: Fix handle activation when monitor device is already set up

### PR DESCRIPTION
**Pull request by coderobe**
This fixes https://github.com/bettercap/bettercap/issues/232#issuecomment-548855249

Handle activation will fail when `SetRFMon` is called and the interface is already set up for monitoring - like on `rtl8812au` chipsets which need to be put into monitoring mode separately.

This patch works around the issue by retrying the interface setup without `SetRFMon` after it has failed once. It is implemented like this because gopacket does not have facilities for checking the monitoring status of a given interface.

### CODE REVIEW

**Comment by evilsocket** [comment]
@coderobe any chance you can fix the conflict so i can merge? thanks

**Comment by coderobe** [comment]
will do

**Comment by coderobe** [comment]
fixed

**Comment by evilsocket** [comment]
thanks a lot!

**Comment by ajmandourah** [comment]
i don't know if its the same issue or not but right now I have compiled bettercap from source in termux. I have my wlan0 already on monitor mode where airodump-ng works but when trying wifi.recon on I still face the same error. I have pocophone f1 with the echo to con_mode trick to turn wlan0 into monitor.

**Comment by coderobe** [comment]
If you've built it off the current master head the console output will be different - you need to post more information.
Regardless, this PR is the wrong place to debug that.

**Pull request merged**
