### PR TITLE
Some enhancement on windows

### PR DESCRIPTION
**Pull request by puppywang**
1. The old way to check ipv4 forwaring status on windows is not correct, the dump contains all interface forwarding status, not the one we required, so the new way use `show interface` instead.

2. Make UI's path in windows default to caplets path.
3. Allow to match iface.Name when matching iface param.

### CODE REVIEW

**Comment by evilsocket** [comment]
why the changed on dns.spoof and the other changes unrelated to what you explained in your comment?

**Comment by puppywang** [comment]
> why the changed on dns.spoof and the other changes unrelated to what you explained in your comment?

I add `dns.spoof.all` flag to dns_spoof module to solve the dns request not forwarded issue on my window machine, the dns server is on the same ip as the gateway, when I do arp-spoof, the target did pass the dns query to me, but the windows refuse to forward those dns request to real gateway, making target unable to do dns resolve, so I add this flag to solve those dns request on upper layer in side dns_spoof module.

**Comment by buffermet** [comment]
I think this recurring suggestion calls for a `dns.server` module rather than a refactoring of the `dns.spoof` module.

**Comment by buffermet** [comment]
I believe that would also solve a dnsmasq issue I ran into when building a captive portal packet proxy for bettercap, but it may have been a routing issue on my end.

**Comment by puppywang** [comment]
> I think this recurring suggestion calls for a `dns.server` or `dns.proxy` module (with scripts?) rather than a refactoring of the current `dns.spoof` module.
> 
> Edit: see [#496 (comment)](https://github.com/bettercap/bettercap/pull/496#issuecomment-473662105)

You are right, after that MR is landed, my issue is fixed and changes to dns.spoof can be reverted, I will revert those codes in dns.spoof.

**Comment by buffermet** [comment]
@puppywang 

> You are right, after that MR is landed, my issue is fixed and changes to dns.spoof can be reverted, I will revert those codes in dns.spoof.

A dns.proxy module has been implemented. More info can be found here: https://github.com/bettercap/bettercap/pull/1143

**Pull request closed without merging**
