### PR TITLE
session: Swap Error Returns

### PR DESCRIPTION
**Pull request by alrs**
Switch to standard `res, err := func()` pattern throughout `session` package and all calling functions.

### CODE REVIEW

**Comment by alrs** [comment]
All that's left after this one are `packet` and `modules`.

**Comment by alrs** [comment]
These signature-swap PRs are pretty invasive, so I'm hesitant to start the next ones for fear of falling into a conflict-rebase hole if this isn't merged first.

**Comment by alrs** [comment]
Is there an official `#bettercap` IRC channel somewhere?

**Comment by evilsocket** [comment]
these core changes need to be discussed first

**Comment by alrs** [comment]
Hi, @evilsocket. Where is the best place to discuss these changes?

**Comment by alrs** [comment]
Hi, @evilsocket. My two previous PRs to standardize function return order landed without issue, what can I do to bring this one back to life?

**Pull request closed without merging**
