### PR TITLE
Add option to manually specify the gateway

### PR DESCRIPTION
**Pull request by rhaidiz**
Sometimes I have the need to perform a MITM between two machines none of which is the default gateway. I find it useful to have the possibility to manually specify the IP address of the "other machine " to MITM. I guess calling it gateway is technically wrong, but it also not worth it to change the entire nomenclature at this stage. I've also updated the wiki on my repo but apparently I cannot create a pull request for that ... too bad.

### CODE REVIEW

**Comment by evilsocket** [comment]
`I guess calling it gateway is technically wrong, but it also not worth it to change the entire nomenclature at this stage` ... I disagree, calling this `gw` or `gateway` is not only wrong, but it's confusing for the end user.

**Comment by rhaidiz** [comment]
Yes, sorry, I meant it's not worth it to change the nomenclature of all the vars inside the source code. It might actually be better to change the nomenclature of the parameter.

**Comment by rhaidiz** [comment]
How do you feel about changing the parameter in something like `main-target` and the description in `Use the provided main target IP address instead of the default gateway.`? My thought is that in general we're MITM the communication that passes via the default gateway, thus we might consider it as the main target. I guess that in this case is also implicit that if the main target is not provided, the default gateway will be used.

**Comment by evilsocket** [comment]
I think `--gateway-override` would be more correct, no?

**Comment by rhaidiz** [comment]
Yep, sounds good. I updated the pull request accordingly.

**Pull request merged**
