### PR TITLE
features & bugfixes

### PR DESCRIPTION
**Pull request by realgam3**
##  Bugs fixed: 
- https://github.com/bettercap/bettercap/issues/591
- https://github.com/bettercap/bettercap/issues/602
Bettercap had an issue download and open caplets on windows

##  Features added:
1)  sending http request from caplets (for example to parse packet using an api)
```javascript
function onLoad() {
    log("module loaded")
    log(httpRequest("GET", "http://httpbin.org/get").body)
    log(httpRequest("POST", "http://httpbin.org/post", "data=data").body)
    log(httpRequest("POST", "http://httpbin.org/post", JSON.stringify({"json": "json"}), {"Content-Type": "application/json"}).body)
}
//Todo: Add more items to the Response object
```
2) drop packets from onData event using a callback
```javascript
function onData(from, to, data, drop) {
    if(readFile('/tmp/drop') == 1) {
        log("Packet Dropped")
        return drop()
    }
    return data
}
```

### CODE REVIEW

**Comment by evilsocket** [comment]
thanks a ton!

**Comment by realgam3** [comment]
No problem :)
Thank you!

I found out there are some more hard coded paths (like ui and all other cap/js files)
So I thought about a way to fix it but it will break the old versions of battercap because battercap caplets built with hard those coded paths :(

The only way not to break it will be to change the archive download link and change the branch of caplets repo to a new branch + not updating the master branch.
Or thinking on another method to fix the hard coded paths like another function that will search and replace the hard coded paths for the windows users.

https://github.com/bettercap/bettercap/compare/master...realgam3:realgam3_features?expand=1
https://github.com/realgam3/caplets/commit/8e088ba87a2292671f35358ee7f3322d21fa40ea

Let me know what you think :)

**Comment by evilsocket** [comment]
those paths are valid everywhere but on Windows ... i'd say windows users can just path the caplets they need themselves :D

**Comment by realgam3** [comment]
> those paths are valid everywhere but on Windows ... i'd say windows users can just path the caplets they need themselves :D

I found a way to will be better for both :)
all we need to do is just to change the paths to relative paths and we are done.
I will add a pull request with the changes :P

**Pull request merged**
